public class CourseEntry 
{
    private String courseCode;
    private String description;

    //autogenerated constructor and getters

    public CourseEntry(String courseCode, String description) {
        this.courseCode = courseCode;
        this.description = description;
    }

    public String getCourseCode() {
        return courseCode;
    }

    public String getDescription() {
        return description;
    }
    
    
}
