public class StudentEntry 
{
    private String studentID;
    private String firstName;
    private String lastName;
    //autogenerated constructor and getters

    public StudentEntry(String studentID, String firstName, String lastName) {
        this.studentID = studentID;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public String getStudentID() {
        return studentID;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }
    
    //overwritten to String method
    public String toString()
    {
        return this.firstName + " " + this.lastName + " " + this.studentID;
    }
}
